# environment
language: python
python:
  - "3.7"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install --editable .

# run tests
script:
    - pylint *.py
    - pytest
    - pytest --cov
